GET http://localhost:5279/dbconexion

###

GET http://localhost:5279/tasksAll

###

GET https://localhost:7174/getTask/Limpiar%20la%20casa

###

POST http://localhost:7174/createTask
Content-Type: application/json
{
  "IdTask":"132fdfb7-a245-42b2-9053-5e20b2a92062",
  "PriorityTask": 0,
  "TaskName": "Cuidar zaira",
  "CategoryID": "f4dd7e80-b991-4992-8207-fdf90ac21b02"
}

### 

PATCH https://localhost:7174/modifiedTask/Limpiar%20la%20casa
Content-Type: application/json
{
  "PriorityTask": 0,
  "TaskName": "Cuidar zaira"
}

###

DELETE https://localhost:7174/deleteTask/Limpiar%20la%20casa



